# Generated by Django 5.1.2 on 2024-11-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='skill_type',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Tools', 'Tools')], default='Frontend', max_length=20),
            preserve_default=False,
        ),
    ]
